version: '3'
services: 
    web:
        # build: .
        build: 
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        # volumes: # we cannot use volume mapping because we do not use wsl.
        #     - /app/node_modules
        #     - .:/app
    tests:
        build: 
            context: .
            dockerfile: Dockerfile.dev 
        # volumes: # we cannot use volume mapping because we do not use wsl.
        #     - /app/node_modules
        #     - .:/app
        command: ["npm", "run", "test"]



# docker-compose up
# docker-compose up --build

# If you are using any version of Windows and your React app is not automatically reloading after a code change, you can add this environment variable to your compose file:

#     services:
#       web:
#         environment:
#           - CHOKIDAR_USEPOLLING=true

