FROM node:alpine

WORKDIR '/app'

COPY package.json .
RUN npm install

COPY . .

CMD ["npm", "run", "start"]


# $ docker build -f Dockerfile.dev .
# delete the "node_modules" directory and rebuild. otherwise it is very large.